clear:
	rm mainfiles/chapter1.aux mainfiles/chapter2.aux mainfiles/chapter3.aux mainfiles/chapter4.aux mainfiles/chapter5.aux mainfiles/intro.aux mainfiles/conclusion.aux
	rm diploma.aux diploma.bbl  diploma.blg  diploma.toc diploma.log diploma.out 