clear:
	rm diploma.aux diploma.bbl diploma.bcf diploma.blg diploma.run.xml diploma.toc diploma.log diploma.out 
	rm mainfiles/chapter1.aux mainfiles/chapter2.aux mainfiles/chapter3.aux mainfiles/chapter4.aux mainfiles/chapter5.aux mainfiles/intro.aux mainfiles/conclusion.aux