function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(7)=1/params(2)+params(3)-1;
    ys_(10)=1;
    ys_(9)=1;
    ys_(6)=((1-params(1))^(1-params(1))*params(1)^params(1)/ys_(7)^params(1))^(1/(1-params(1)));
    K2L=params(1)*ys_(6)/ys_(7)/(1-params(1));
    C2L=K2L^params(1)-params(3)*K2L;
    ys_(3)=(ys_(6)/params(6)/C2L^params(4))^(1/(params(4)+params(5)));
    ys_(2)=K2L*ys_(3);
    ys_(4)=C2L*ys_(3);
    ys_(1)=ys_(2)^params(1)*ys_(3)^(1-params(1));
    ys_(5)=params(3)*ys_(2);
    ys_(8)=ys_(1)-ys_(7)*ys_(2)-ys_(6)*ys_(3);
    % Auxiliary equations
end
